### ISSUE TITLE
Create task list and project board to manage work over the next quarter

### ISSUE THREAD

**Issue by malvikasharan** [aphrc-dswb/ospo-now-dswb#1]
### Summary

* We should share our work plan and create project board reflecting the responsibilities and task lists in DSWB

### What needs to be done?

- [ ] Describe main goals and deliverables: Should each be on their own project board?
- [ ] Define operational work and assign to right people
- [ ] Review project board in regular meetings

### Who can help?

* Raphael and Precious

---

### Updates

*
